[2024-04-08T18:58:15.837+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: seed_initial_data.insert_coins_into_db manual__2024-04-08T18:58:15.052672+00:00 [queued]>
[2024-04-08T18:58:15.844+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: seed_initial_data.insert_coins_into_db manual__2024-04-08T18:58:15.052672+00:00 [queued]>
[2024-04-08T18:58:15.845+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-04-08T18:58:15.853+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_coins_into_db> on 2024-04-08 18:58:15.052672+00:00
[2024-04-08T18:58:15.858+0000] {standard_task_runner.py:57} INFO - Started process 72085 to run task
[2024-04-08T18:58:15.862+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'seed_initial_data', 'insert_coins_into_db', 'manual__2024-04-08T18:58:15.052672+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/file_procesor_dag.py', '--cfg-path', '/tmp/tmpcwfh6sys']
[2024-04-08T18:58:15.864+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask insert_coins_into_db
[2024-04-08T18:58:15.914+0000] {task_command.py:416} INFO - Running <TaskInstance: seed_initial_data.insert_coins_into_db manual__2024-04-08T18:58:15.052672+00:00 [running]> on host 2c889d8e7a74
[2024-04-08T18:58:15.986+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='seed_initial_data' AIRFLOW_CTX_TASK_ID='insert_coins_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T18:58:15.052672+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T18:58:15.052672+00:00'
[2024-04-08T18:58:15.989+0000] {logging_mixin.py:154} INFO - {'origin_path': 'scripts/data/config/nyse_2012.csv', 'final_path': 'nyse_2012_ts.parquet', 'metadata': {'type': 'DELIMITED', 'columns_width': [6, 24, 7, 7, 7, 7, 7], 'columns_name': ['stock', 'transaction_date', 'open_price', 'close_price', 'max_price', 'min_price', 'variation'], 'additional_data': {}}, 'partition_by': 'stock'}
[2024-04-08T18:58:15.990+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/main.py", line 13, in procesar_archivo
    strategy = get_strategy(config['metadata']['type'])
  File "/opt/airflow/scripts/strategies/read.py", line 34, in get_strategy
    strategy = strategy_map[strategy_type]
KeyError: 'DELIMITED'
[2024-04-08T18:58:16.002+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=seed_initial_data, task_id=insert_coins_into_db, execution_date=20240408T185815, start_date=20240408T185815, end_date=20240408T185816
[2024-04-08T18:58:16.010+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task insert_coins_into_db ('DELIMITED'; 72085)
[2024-04-08T18:58:16.034+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-08T18:58:16.055+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
